name: Update README2

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Update Profile README
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update recent activity
        uses: Readme-Workflows/recent-activity@a0648ccdc745a4597623df25cfc1150652f8a7ca
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
