name: Update README2

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update Profile README

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update recent activity
        uses: Readme-Workflows/recent-activity@<latest-supported-version>
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
